services:
  postgres:
    image: postgres:15-alpine
    container_name: sentinelqueue-postgres
    environment:
      POSTGRES_USER: sentinel
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sentinelqueue
    ports:
      - "5440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: sentinelqueue-redis
    ports:
      - "6385:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
